<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.CN.NET.Sdk/14.0.0">
  <PropertyGroup>
    <Title>BlindBoxPlugin</Title>
    <Version>1.9.1.0</Version>
    <Description>A blind box plugin.</Description>
    <PackageProjectUrl>https://github.com/yimo0908/FFXIVBlindBoxPlugin</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="FFXIVClientStructs">
      <HintPath>$(DalamudLibPath)FFXIVClientStructs.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
